//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantLocator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Cuisine { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Postcode { get; set; }
        public string Phone_Number { get; set; }
        public string Price_Range { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
    }
}
